language: nix
nix: 2.3.2
script:
  - nix-env -iA cachix -f https://cachix.org/api/v1/install
  - cachix use thought2
  - nix-env -i nixops

  - nixops delete --all --force
  - nixops create src/nix/network.nix src/nix/network-stage.nix -d stage
  - nixops create src/nix/network.nix src/nix/network-prod.nix -d prod

  - export NIX_PATH=""; cachix push thought2 --watch-store & nixops deploy -d stage --build-only;
  - export NIX_PATH=""; cachix push thought2 --watch-store & nixops deploy -d prod --build-only;

  - |
    if [ "$TRAVIS_BRANCH" = "stage" ]; then
      echo "STAGE DEPLOYMENT";
      export NIX_PATH=""; cachix push thought2 --watch-store & nixops deploy -d stage;
    fi

  - |
    if [ "$TRAVIS_BRANCH" = "master" && $TRAVIS_PULL_REQUEST != "false" ]; then
      echo "PROD DEPLOYMENT (DRY-RUN)";
      export NIX_PATH=""; cachix push thought2 --watch-store & nixops deploy -d prod --copy-only;
    fi

  - |
    if [ "$TRAVIS_BRANCH" = "master" && $TRAVIS_PULL_REQUEST = "false" ]; then
      echo "PROD DEPLOYMENT";
      export NIX_PATH=""; cachix push thought2 --watch-store & nixops deploy -d prod;
    fi
before_install:
  - openssl aes-256-cbc -K $encrypted_6f3005cf51f5_key -iv $encrypted_6f3005cf51f5_iv
    -in deploy_key.enc -out ./deploy_key -d
  - eval "$(ssh-agent -s)"
  - chmod 600 ./deploy_key
  - chmod 600 ~/.ssh/config
  - echo -e "Host stage.thought2.de\n\tStrictHostKeyChecking no\n" >> ~/.ssh/config
  - echo -e "Host thought2.de\n\tStrictHostKeyChecking no\n" >> ~/.ssh/config
  - ssh-add ./deploy_key
