language: nix
nix: 2.3.2
script:
  - nix-env -i nixops
  - nixops create -d simple src/nix/network.nix
  - nixops deploy -d simple
before_install:
  - openssl aes-256-cbc -K $encrypted_6f3005cf51f5_key -iv $encrypted_6f3005cf51f5_iv
    -in deploy_key.enc -out ./deploy_key -d
  - ssh-add ./deploy_key
