language: nix
nix: 2.3.2
script:
  - nix-env -i nixops
  - nixops create -d simple src/nix/network.nix
  - nixops deploy -d simple
before_install:
  - openssl aes-256-cbc -K $encrypted_6f3005cf51f5_key -iv $encrypted_6f3005cf51f5_iv
    -in deploy_key.enc -out ./deploy_key -d
  - eval "$(ssh-agent -s)"
  - chmod 600 ./deploy_key
  - echo -e "Host stage.thought2.de\n\tStrictHostKeyChecking no\n" >> ~/.ssh/config
  - ssh-add ./deploy_key
